# Generated by Django 5.0.7 on 2024-07-28 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=50)),
                ('kod', models.CharField(blank=True, max_length=50)),
                ('zobrazit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hodnota', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrazek', models.URLField()),
                ('nazev', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mena', models.CharField(blank=True, max_length=10)),
                ('published_on', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.attributename')),
                ('hodnota_atributu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.attributevalue')),
            ],
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('nazev', models.CharField(blank=True, max_length=250)),
                ('attributes_ids', models.ManyToManyField(blank=True, to='dataparser.attribute')),
                ('obrazek_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataparser.image')),
                ('products_ids', models.ManyToManyField(blank=True, to='dataparser.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAttributes',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.PositiveBigIntegerField(blank=True, primary_key=True, serialize=False)),
                ('nazev', models.CharField(max_length=250)),
                ('obrazek_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataparser.product')),
            ],
        ),
    ]
